"""Write draft YAML files alongside model SQL files."""

from __future__ import annotations

import re
from pathlib import Path

from dbt_autodoc.manifest import ModelInfo


def extract_yaml_from_response(response: str) -> str:
    """Extract YAML content from an LLM response, stripping code fences."""
    # Try to extract from ```yaml ... ``` block
    match = re.search(r"```ya?ml\s*\n(.*?)```", response, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Try to extract from generic ``` ... ``` block
    match = re.search(r"```\s*\n(.*?)```", response, re.DOTALL)
    if match:
        return match.group(1).strip()

    # No code fences — return as-is (might already be plain YAML)
    return response.strip()


def build_draft_yaml(model_name: str, yaml_content: str) -> str:
    """Wrap extracted YAML content into a complete schema file."""
    lines = [
        "# =============================================================================",
        f"# Draft descriptions for model: {model_name}",
        "# Generated by dbt-autodoc (LLM mode)",
        "#",
        "# Review these descriptions carefully before merging into your schema files.",
        "# =============================================================================",
        "",
        "version: 2",
        "",
        "models:",
    ]

    # If the YAML content already starts with "- name:" or "  - name:", use as-is
    content = yaml_content.strip()
    if content.startswith("- name:") or content.startswith("  - name:"):
        # Ensure proper indentation (2 spaces under models:)
        for line in content.splitlines():
            stripped = line.lstrip()
            if stripped.startswith("- name:"):
                lines.append(f"  {stripped}")
            elif stripped:
                # Preserve relative indentation
                leading = len(line) - len(stripped)
                lines.append(f"  {'  ' * (leading // 2)}{stripped}")
            else:
                lines.append("")
    else:
        # Fallback: include raw content
        lines.append(content)

    lines.append("")
    return "\n".join(lines)


def write_draft_file(model: ModelInfo, yaml_content: str, project_dir: Path) -> Path:
    """Write a draft_<modelname>.yml file next to the model's SQL file."""
    # Determine the output path
    model_sql_path = project_dir / model.original_file_path
    model_dir = model_sql_path.parent
    draft_filename = f"draft_{model.name}.yml"
    draft_path = model_dir / draft_filename

    # Build full YAML content
    full_yaml = build_draft_yaml(model.name, yaml_content)

    # Write the file
    model_dir.mkdir(parents=True, exist_ok=True)
    draft_path.write_text(full_yaml)

    return draft_path
