{% macro generate_descriptions(model_name=none) %}
    {#
        Generates draft YAML descriptions for dbt models using heuristic inference.

        Usage:
            dbt run-operation generate_descriptions --args '{model_name: stg_orders}'
            dbt run-operation generate_descriptions
    #}

    {% set nodes = [] %}

    {% if model_name %}
        {% for node_id, node in graph.nodes.items() %}
            {% if node.resource_type == 'model' and node.name == model_name %}
                {% do nodes.append(node) %}
            {% endif %}
        {% endfor %}

        {% if nodes | length == 0 %}
            {{ log("dbt-autodoc ERROR: Model '" ~ model_name ~ "' not found in project.", info=true) }}
            {{ return('') }}
        {% endif %}
    {% else %}
        {% for node_id, node in graph.nodes.items() %}
            {% if node.resource_type == 'model' and node.package_name == project_name %}
                {% do nodes.append(node) %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {{ log('dbt-autodoc: Generating descriptions for ' ~ nodes | length ~ ' model(s)...', info=true) }}

    {% set output_lines = [] %}
    {% do output_lines.append('# =============================================================================') %}
    {% if model_name %}
        {% do output_lines.append('# Draft descriptions for model: ' ~ model_name) %}
    {% else %}
        {% do output_lines.append('# Draft descriptions for all models') %}
    {% endif %}
    {% do output_lines.append('# Generated by dbt-autodoc (heuristic mode)') %}
    {% do output_lines.append('#') %}
    {% do output_lines.append('# Review these descriptions carefully before merging into your schema files.') %}
    {% do output_lines.append('# =============================================================================') %}
    {% do output_lines.append('') %}
    {% do output_lines.append('version: 2') %}
    {% do output_lines.append('') %}
    {% do output_lines.append('models:') %}

    {% for node in nodes | sort(attribute='name') %}
        {% set model_desc = dbt_autodoc.infer_model_description(node.name) | trim %}
        {% do output_lines.append('  - name: ' ~ node.name) %}
        {% do output_lines.append('    description: "' ~ model_desc ~ '"') %}

        {% set columns = adapter.get_columns_in_relation(ref(node.name)) %}

        {% if columns | length > 0 %}
            {% do output_lines.append('    columns:') %}
            {% for col in columns %}
                {% set col_desc = dbt_autodoc.infer_column_description(col.name, col.dtype) | trim %}
                {% do output_lines.append('      - name: ' ~ col.name) %}
                {% do output_lines.append('        description: "' ~ col_desc ~ '"') %}
            {% endfor %}
        {% endif %}

        {% do output_lines.append('') %}
    {% endfor %}

    {% for line in output_lines %}
        {{ log(line, info=true) }}
    {% endfor %}

    {{ log('dbt-autodoc: Done.', info=true) }}
{% endmacro %}
