{% macro generate_descriptions(model_name=none, output_path=none) %}
    {#
        Generates draft YAML descriptions for dbt models using heuristic inference.

        Usage (print to terminal):
            dbt run-operation generate_descriptions
            dbt run-operation generate_descriptions --args '{model_name: stg_orders}'

        Usage (write to file automatically):
            dbt run-operation generate_descriptions --args '{model_name: stg_orders}'
            ^ Writes draft_stg_orders.yml next to the model's .sql file

        Usage (custom output path):
            dbt run-operation generate_descriptions --args '{model_name: stg_orders, output_path: my_draft.yml}'
    #}

    {# Retrieve all nodes from the dbt graph #}
    {% set nodes = [] %}

    {% if model_name %}
        {% for node_id, node in graph.nodes.items() %}
            {% if node.resource_type == 'model' and node.name == model_name %}
                {% do nodes.append(node) %}
            {% endif %}
        {% endfor %}

        {% if nodes | length == 0 %}
            {{ log("ERROR: Model '" ~ model_name ~ "' not found in project.", info=true) }}
            {{ return('') }}
        {% endif %}
    {% else %}
        {% for node_id, node in graph.nodes.items() %}
            {% if node.resource_type == 'model' and node.package_name == project_name %}
                {% do nodes.append(node) %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {{ log('dbt-autodoc: Generating descriptions for ' ~ nodes | length ~ ' model(s)...', info=true) }}

    {# Build the YAML content #}
    {% set output_lines = [] %}

    {% do output_lines.append('# =============================================================================') %}
    {% if model_name %}
        {% do output_lines.append('# Draft descriptions for model: ' ~ model_name) %}
    {% else %}
        {% do output_lines.append('# Draft descriptions for all models') %}
    {% endif %}
    {% do output_lines.append('# Generated by dbt-autodoc (heuristic mode)') %}
    {% do output_lines.append('#') %}
    {% do output_lines.append('# Review these descriptions carefully before merging into your schema files.') %}
    {% do output_lines.append('# =============================================================================') %}
    {% do output_lines.append('') %}
    {% do output_lines.append('version: 2') %}
    {% do output_lines.append('') %}
    {% do output_lines.append('models:') %}

    {% for node in nodes | sort(attribute='name') %}
        {% set model_desc = dbt_autodoc.infer_model_description(node.name) | trim %}
        {% do output_lines.append('  - name: ' ~ node.name) %}
        {% do output_lines.append('    description: "' ~ model_desc ~ '"') %}

        {# Get columns from the database if the model is materialized #}
        {% set columns = adapter.get_columns_in_relation(ref(node.name)) %}

        {% if columns | length > 0 %}
            {% do output_lines.append('    columns:') %}
            {% for col in columns %}
                {% set col_desc = dbt_autodoc.infer_column_description(col.name, col.dtype) | trim %}
                {% do output_lines.append('      - name: ' ~ col.name) %}
                {% do output_lines.append('        description: "' ~ col_desc ~ '"') %}
            {% endfor %}
        {% endif %}

        {% do output_lines.append('') %}
    {% endfor %}

    {% set yaml_content = output_lines | join('\n') %}

    {# Determine file path: auto-detect from model or use custom path #}
    {% set write_path = none %}

    {% if output_path %}
        {% set write_path = output_path %}
    {% elif model_name and nodes | length == 1 %}
        {# Auto-generate path: draft_<modelname>.yml next to the .sql file #}
        {% set model_node = nodes[0] %}
        {% set model_file_path = model_node.original_file_path %}
        {% set path_parts = model_file_path.split('/') %}
        {% set dir_parts = path_parts[:-1] %}
        {% set draft_filename = 'draft_' ~ model_name ~ '.yml' %}
        {% set write_path = dir_parts | join('/') ~ '/' ~ draft_filename %}
    {% endif %}

    {% if write_path %}
        {# Write to file using Python's open() via Jinja #}
        {% set project_root = modules.os.getcwd() %}
        {% set full_path = project_root ~ '/' ~ write_path %}

        {% do modules.os.makedirs(modules.os.path.dirname(full_path), exist_ok=true) %}

        {% set f = modules.builtins.open(full_path, 'w') %}
        {% do f.write(yaml_content) %}
        {% do f.close() %}

        {{ log('dbt-autodoc: Written to ' ~ write_path, info=true) }}
    {% else %}
        {# No model specified or multiple models — print to terminal #}
        {% for line in output_lines %}
            {{ log(line, info=true) }}
        {% endfor %}
        {{ log('', info=true) }}
        {{ log('dbt-autodoc: Tip — specify model_name to auto-write a draft file.', info=true) }}
    {% endif %}
{% endmacro %}
