{% macro generate_descriptions(model_name=none) %}
    {#
        Generates draft YAML descriptions for dbt models using heuristic inference.

        Usage:
            dbt run-operation generate_descriptions --args '{model_name: stg_orders}'
            dbt run-operation generate_descriptions --args '{model_name: stg_orders}' > models/staging/draft_stg_orders.yml
            dbt run-operation generate_descriptions > draft_all_models.yml

        print() sends YAML to stdout (captured by >).
        log() sends status messages to stderr (shown in terminal).
    #}

    {# Retrieve all nodes from the dbt graph #}
    {% set nodes = [] %}

    {% if model_name %}
        {% for node_id, node in graph.nodes.items() %}
            {% if node.resource_type == 'model' and node.name == model_name %}
                {% do nodes.append(node) %}
            {% endif %}
        {% endfor %}

        {% if nodes | length == 0 %}
            {{ log("ERROR: Model '" ~ model_name ~ "' not found in project.", info=true) }}
            {{ return('') }}
        {% endif %}
    {% else %}
        {% for node_id, node in graph.nodes.items() %}
            {% if node.resource_type == 'model' and node.package_name == project_name %}
                {% do nodes.append(node) %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {{ log('dbt-autodoc: Generating descriptions for ' ~ nodes | length ~ ' model(s)...', info=true) }}

    {# Use print() so output goes to stdout — clean capture with > #}
    {{ print('# =============================================================================') }}
    {% if model_name %}
        {{ print('# Draft descriptions for model: ' ~ model_name) }}
    {% else %}
        {{ print('# Draft descriptions for all models') }}
    {% endif %}
    {{ print('# Generated by dbt-autodoc (heuristic mode)') }}
    {{ print('#') }}
    {{ print('# Review these descriptions carefully before merging into your schema files.') }}
    {{ print('# =============================================================================') }}
    {{ print('') }}
    {{ print('version: 2') }}
    {{ print('') }}
    {{ print('models:') }}

    {% for node in nodes | sort(attribute='name') %}
        {% set model_desc = dbt_autodoc.infer_model_description(node.name) | trim %}
        {{ print('  - name: ' ~ node.name) }}
        {{ print('    description: "' ~ model_desc ~ '"') }}

        {# Get columns from the database if the model is materialized #}
        {% set columns = adapter.get_columns_in_relation(ref(node.name)) %}

        {% if columns | length > 0 %}
            {{ print('    columns:') }}
            {% for col in columns %}
                {% set col_desc = dbt_autodoc.infer_column_description(col.name, col.dtype) | trim %}
                {{ print('      - name: ' ~ col.name) }}
                {{ print('        description: "' ~ col_desc ~ '"') }}
            {% endfor %}
        {% endif %}

        {{ print('') }}
    {% endfor %}

    {{ log('dbt-autodoc: Done. Pipe to a file with > to save.', info=true) }}
{% endmacro %}
